services:
  # backend:
  #   image: node:20.11.1-alpine
  #   container_name: nest-app-test
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #     - /usr/src/app/node_modules # Empêche les conflits entre les node_modules en local et dans le conteneur
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run start:dev
  #   depends_on:
  #     - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: nestapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestapp
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
