# Use Node.js 20.11.1 base image
FROM node:20.11.1-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm cache clean --force
RUN npm install --legacy-peer-deps

# Generate Prisma Client code
RUN npx prisma generate

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app
CMD [  "npm", "run", "start:dev" ]